
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/game/game.native.js",
	"libs/modules/res/res.js",
	"libs/modules/gui/gui.js",
	"libs/modules/dragonBones/dragonBones.js",
	"libs/modules/socket/socket.js",
	"libs/modules/tween/tween.js",
	"libs/protobuf/ByteBufferAB.min.js",
	"libs/protobuf/Long.min.js",
	"libs/protobuf/ProtoBuf.min.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/Main.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/core/App.js",
	"bin-debug/core/adapter/AssetAdapter.js",
	"bin-debug/core/adapter/MergeJsonAnalyzer.js",
	"bin-debug/core/base/BaseClass.js",
	"bin-debug/core/consts/Keyboard.js",
	"bin-debug/core/display/BitmapNumber.js",
	"bin-debug/core/display/HotspotBitmap.js",
	"bin-debug/core/dragonBones/DragonBonesArmature.js",
	"bin-debug/core/dragonBones/DragonBonesArmatureContainer.js",
	"bin-debug/core/dragonBones/DragonBonesFactory.js",
	"bin-debug/core/dragonBones/EgretTextureAtlasMore.js",
	"bin-debug/core/module/guide/GuideMaskBackgroud.js",
	"bin-debug/core/module/guide/GuideUtils.js",
	"bin-debug/core/module/guide/GuideView.js",
	"bin-debug/core/module/loading/EasyLoading.js",
	"bin-debug/core/mvc/ControllerManager.js",
	"bin-debug/core/mvc/ViewManager.js",
	"bin-debug/core/mvc/controller/BaseController.js",
	"bin-debug/core/mvc/model/BaseModel.js",
	"bin-debug/core/mvc/proxy/BaseProxy.js",
	"bin-debug/core/mvc/view/BaseGuiView.js",
	"bin-debug/core/mvc/view/BaseSpriteView.js",
	"bin-debug/core/mvc/view/IBaseView.js",
	"bin-debug/core/net/http/DataCache.js",
	"bin-debug/core/net/http/DataUpdate.js",
	"bin-debug/core/net/http/Http.js",
	"bin-debug/core/net/socket/BaseMsg.js",
	"bin-debug/core/net/socket/ByteArrayMsg.js",
	"bin-debug/core/net/socket/ByteArrayMsgByProtobuf.js",
	"bin-debug/core/net/socket/Socket.js",
	"bin-debug/core/net/socket/SocketConst.js",
	"bin-debug/core/net/socket/UTFMsg.js",
	"bin-debug/core/net/socket/UTFMsgByJson.js",
	"bin-debug/core/scene/base/BaseGuiLayer.js",
	"bin-debug/core/scene/base/BaseScene.js",
	"bin-debug/core/scene/base/BaseSpriteLayer.js",
	"bin-debug/core/scene/manager/SceneManager.js",
	"bin-debug/core/sound/BaseSound.js",
	"bin-debug/core/sound/SoundBg.js",
	"bin-debug/core/sound/SoundEffects.js",
	"bin-debug/core/sound/SoundManager.js",
	"bin-debug/core/starlingswf/Swf.js",
	"bin-debug/core/starlingswf/SwfAssetManager.js",
	"bin-debug/core/starlingswf/SwfUpdateManager.js",
	"bin-debug/core/starlingswf/display/ISwfAnimation.js",
	"bin-debug/core/starlingswf/display/SwfSprite.js",
	"bin-debug/core/starlingswf/display/SwfMovieClip.js",
	"bin-debug/core/starlingswf/game/StarlingSwfFactory.js",
	"bin-debug/core/starlingswf/game/StarlingSwfMovieClip.js",
	"bin-debug/core/starlingswf/game/StarlingSwfUtils.js",
	"bin-debug/core/utils/AllAsyncExecutor.js",
	"bin-debug/core/utils/AnchorUtil.js",
	"bin-debug/core/utils/ArrayUtils.js",
	"bin-debug/core/utils/AverageUtils.js",
	"bin-debug/core/utils/CommonUtils.js",
	"bin-debug/core/utils/DateUtils.js",
	"bin-debug/core/utils/DebugUtils.js",
	"bin-debug/core/utils/DelayOptManager.js",
	"bin-debug/core/utils/DeviceUtils.js",
	"bin-debug/core/utils/DisplayUtils.js",
	"bin-debug/core/utils/EffectUtils.js",
	"bin-debug/core/utils/EgretExpandUtils.js",
	"bin-debug/core/utils/FrameDelay.js",
	"bin-debug/core/utils/FrameExecutor.js",
	"bin-debug/core/utils/KeyboardUtils.js",
	"bin-debug/core/utils/LocationProperty.js",
	"bin-debug/core/utils/Log.js",
	"bin-debug/core/utils/MathUtils.js",
	"bin-debug/core/utils/MessageCenter.js",
	"bin-debug/core/utils/ObjectPool.js",
	"bin-debug/core/utils/Percent.js",
	"bin-debug/core/utils/QueueExecutor.js",
	"bin-debug/core/utils/RandomUtils.js",
	"bin-debug/core/utils/RenderTextureManager.js",
	"bin-debug/core/utils/ResVersionManager.js",
	"bin-debug/core/utils/ResourceUtils.js",
	"bin-debug/core/utils/RockerUtils.js",
	"bin-debug/core/utils/ShockUtils.js",
	"bin-debug/core/utils/StageUtils.js",
	"bin-debug/core/utils/StringBuffer.js",
	"bin-debug/core/utils/StringUtils.js",
	"bin-debug/core/utils/TextFlowMaker.js",
	"bin-debug/core/utils/TimerManager.js",
	"bin-debug/core/utils/md5.js",
	"bin-debug/example/components/Menu.js",
	"bin-debug/example/components/SaleItemRenderer.js",
	"bin-debug/example/components/TabBarButton.js",
	"bin-debug/example/components/TabBarContainer.js",
	"bin-debug/example/components/TaskItemRenderer.js",
	"bin-debug/example/consts/ControllerConst.js",
	"bin-debug/example/consts/HttpConst.js",
	"bin-debug/example/consts/SceneConsts.js",
	"bin-debug/example/consts/ViewConst.js",
	"bin-debug/example/module/base/BasePanelView.js",
	"bin-debug/example/module/factory/FactoryController.js",
	"bin-debug/example/module/factory/FactoryView.js",
	"bin-debug/example/module/friend/FriendController.js",
	"bin-debug/example/module/friend/FriendView.js",
	"bin-debug/example/module/game/GameConst.js",
	"bin-debug/example/module/game/GameController.js",
	"bin-debug/example/module/game/GameData.js",
	"bin-debug/example/module/game/GameUIView.js",
	"bin-debug/example/module/game/GameView.js",
	"bin-debug/example/module/game/MyButton.js",
	"bin-debug/example/module/game/object/BaseGameObject.js",
	"bin-debug/example/module/game/object/BaseMoveGameObject.js",
	"bin-debug/example/module/game/object/BaseAIGameObject.js",
	"bin-debug/example/module/game/object/BaseHitGameObject.js",
	"bin-debug/example/module/game/object/BaseFrameGameObject.js",
	"bin-debug/example/module/game/object/Enemy.js",
	"bin-debug/example/module/game/object/Boss.js",
	"bin-debug/example/module/game/object/Hero.js",
	"bin-debug/example/module/home/HomeConst.js",
	"bin-debug/example/module/home/HomeController.js",
	"bin-debug/example/module/home/HomeProxy.js",
	"bin-debug/example/module/home/HomeView.js",
	"bin-debug/example/module/loading/LoadingConst.js",
	"bin-debug/example/module/loading/LoadingController.js",
	"bin-debug/example/module/loading/LoadingView.js",
	"bin-debug/example/module/login/LoginConst.js",
	"bin-debug/example/module/login/LoginController.js",
	"bin-debug/example/module/login/LoginModel.js",
	"bin-debug/example/module/login/LoginProxy.js",
	"bin-debug/example/module/login/LoginView.js",
	"bin-debug/example/module/mail/MailController.js",
	"bin-debug/example/module/mail/MailView.js",
	"bin-debug/example/module/shop/ShopController.js",
	"bin-debug/example/module/shop/ShopView.js",
	"bin-debug/example/module/task/BaseTaskView.js",
	"bin-debug/example/module/task/DailyView.js",
	"bin-debug/example/module/task/TaskController.js",
	"bin-debug/example/module/task/TaskView.js",
	"bin-debug/example/module/warehouse/WarehouseController.js",
	"bin-debug/example/module/warehouse/WarehouseView.js",
	"bin-debug/example/scene/GameScene.js",
	"bin-debug/example/scene/LayerManager.js",
	"bin-debug/example/scene/LoadingScene.js",
	"bin-debug/example/scene/UIScene.js",
	"bin-debug/example/test/ActTest.js",
	"bin-debug/example/test/GUITest.js",
	"bin-debug/example/test/ProtoBufTest.js",
	"bin-debug/example/test/StarlingSwfTest.js",
	"bin-debug/skins/GuiScreenSkin.g.js",
	"bin-debug/skins/ListSkin.g.js",
	"bin-debug/skins/LoadingUISkin.g.js",
	"bin-debug/skins/MenuButtonSkin.g.js",
	"bin-debug/skins/MenuSkin.g.js",
	"bin-debug/skins/PanelButtonSkin.g.js",
	"bin-debug/skins/PanelSkin.g.js",
	"bin-debug/skins/SaleItemSkin.g.js",
	"bin-debug/skins/TabBarButtonSkin.g.js",
	"bin-debug/skins/TabBarSkin.g.js",
	"bin-debug/skins/TaskItemRendererSkin.g.js",
	"bin-debug/skins/TileListSkin.g.js",
	"bin-debug/skins/simple/AlertSkin.g.js",
	"bin-debug/skins/simple/ButtonSkin.g.js",
	"bin-debug/skins/simple/CheckBoxSkin.g.js",
	"bin-debug/skins/simple/CloseButtonSkin.g.js",
	"bin-debug/skins/simple/DropDownListItemRendererSkin.g.js",
	"bin-debug/skins/simple/DropDownListOpenButtonSkin.g.js",
	"bin-debug/skins/simple/DropDownListSkin.g.js",
	"bin-debug/skins/simple/HScrollBarSkin.g.js",
	"bin-debug/skins/simple/HScrollBarThumbSkin.g.js",
	"bin-debug/skins/simple/HSliderSkin.g.js",
	"bin-debug/skins/simple/HSliderThumbSkin.g.js",
	"bin-debug/skins/simple/ItemRendererSkin.g.js",
	"bin-debug/skins/simple/ListSkin.g.js",
	"bin-debug/skins/simple/PanelSkin.g.js",
	"bin-debug/skins/simple/ProgressBarSkin.g.js",
	"bin-debug/skins/simple/RadioButtonSkin.g.js",
	"bin-debug/skins/simple/ScrollerSkin.g.js",
	"bin-debug/skins/simple/SkinnableContainerSkin.g.js",
	"bin-debug/skins/simple/SkinnableDataContainer.g.js",
	"bin-debug/skins/simple/SliderThumbSkin.g.js",
	"bin-debug/skins/simple/TabBarButtonSkin.g.js",
	"bin-debug/skins/simple/TabBarSkin.g.js",
	"bin-debug/skins/simple/TextAreaSkin.g.js",
	"bin-debug/skins/simple/TextInputSkin.g.js",
	"bin-debug/skins/simple/TitleWindowSkin.g.js",
	"bin-debug/skins/simple/ToggleButtonSkin.g.js",
	"bin-debug/skins/simple/ToggleSwitchSkin.g.js",
	"bin-debug/skins/simple/TreeDisclosureButtonSkin.g.js",
	"bin-debug/skins/simple/TreeItemRendererSkin.g.js",
	"bin-debug/skins/simple/TreeSkin.g.js",
	"bin-debug/skins/simple/VScrollBarSkin.g.js",
	"bin-debug/skins/simple/VScrollBarThumbSkin.g.js",
	"bin-debug/skins/simple/VSliderSkin.g.js",
	"bin-debug/skins/simple/VSliderThumbSkin.g.js",
	//----auto game_file_list end----
];

var window = {};

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "fixedWidth",
		contentWidth: 960,
		contentHeight: 640,
		showPaintRect: false,
		showFPS: true,
		fpsStyles: "x:0,y:0,size:30,textColor:0x00c200,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};